package com.vishakha.position_doctor_project.domain.diagnostic.dto;

import com.vishakha.position_doctor_project.common.dto.RiskLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Diagnostic analysis report generated by Position Doctor engine.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PositionHealthReportDto {

    private String reportId;
    private String positionId;
    private int healthScore; // 0 to 100
    private RiskLevel overallRiskLevel;
    private RiskMetricsDto riskMetrics;
    private List<String> recommendations;
    private List<String> warningFlags;
    private LocalDateTime generatedAt;
}
