package com.vishakha.position_doctor_project.domain.diagnostic.dto;

import com.vishakha.position_doctor_project.common.dto.RiskLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Diagnostic health report output DTO generated by Position Doctor engine.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PositionHealthReport {

    private UUID positionId;
    private String symbol;
    private int healthScore; // Range: 0 to 100
    private RiskLevel riskLevel;
    private RecommendationAction recommendation;
    private String reason;
}
